executable              = scripts/run_everything.sh
arguments               = $(ClusterID) $(ProcId) background_ttbar
transfer_input_files    = simulation, scripts/run_everything.sh
transfer_output_files   = ttbarBackground_2000_$(ProcId).root
when_to_transfer_output = ON_EXIT

output                  = logs/output/std.$(ClusterId).$(ProcId).out
error                   = logs/error/std.$(ClusterId).$(ProcId).err
log                     = logs/std.$(ClusterId).log

+JobFlavour             = "tomorrow"

queue 1000
